apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notifiarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifiarr
  template:
    metadata:
      labels:
        app: notifiarr
    spec:
      containers:
        - name: notifiarr
          image: golift/notifiarr:0.8.3

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"

          ports:
            - containerPort: 5454
          volumeMounts:
            - name: config
              mountPath: /config
            - name: machine-id
              mountPath: /etc/machine-id
      volumes:
        - name: config
          hostPath:
            path: /mnt/data/configs/notifiarr
            type: Directory
        - name: machine-id
          hostPath:
            path: /etc/machine-id
            type: File
