network:
    version: 2
    ethernets:
      enp2s0:
          dhcp4: false
          addresses:
            - 10.0.0.10/24
          routes:
            - to: default
              via: 10.0.0.138
          nameservers:
            addresses:
              - 8.8.8.8
              - 1.1.1.1
