---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helm-deployments
  namespace: flux-system
spec:
  interval: 1m
  path: ./terraform/        # relative to your Git repo root
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: flux-system       # name of your GitRepository resource
  backendConfig:
    disable: true           # disable remote state backend for now
  runnerPodTemplate:
    spec:
      serviceAccountName: default  # optional, or customize if needed
