apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: authentik-secret
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: /homelab/authentik/AUTHENTIK_SECRET_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /homelab/authentik/POSTGRES_PASSWORD
