apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: "2025.8.3"
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: authentik
  values:
    authentik:
      # secret_key is injected via valuesFrom below
      error_reporting:
        enabled: true
      postgresql:
        # password is injected via valuesFrom
        # other connection params use chart defaults when bundled Postgres is enabled
        {}

    # TRAEFIK + PLAIN HTTP AT ORIGIN (Cloudflare Tunnel handles TLS)
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
        - auth.${BASE_DOMAIN}
        - auth.homelab

    # Bundle Postgres & Redis 
    postgresql:
      enabled: true
      auth:
        # password injected via valuesFrom
        {}
      primary:
        persistence:
          enabled: true
          size: 8Gi

    redis:
      enabled: true

  valuesFrom:
  - kind: Secret
    name: authentik-secret
    valuesKey: AUTHENTIK_SECRET_KEY
    targetPath: authentik.secret_key
  - kind: Secret
    name: authentik-secret
    valuesKey: POSTGRES_PASSWORD
    targetPath: postgresql.auth.password
  - kind: Secret
    name: authentik-secret
    valuesKey: POSTGRES_PASSWORD
    targetPath: authentik.postgresql.password
