apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-postgresql-nfs
spec:
  capacity:
    storage: 8Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_ROOT}/authentik-postgresql
  claimRef:
    namespace: authentik
    name: authentik-postgresql-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgresql-nfs
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeName: authentik-postgresql-nfs
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-redis-nfs
spec:
  capacity:
    storage: 8Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_ROOT}/authentik-redis
  claimRef:
    namespace: authentik
    name: authentik-redis-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-nfs
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeName: authentik-redis-nfs
  resources:
    requests:
      storage: 8Gi
