apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:lY607k1sdG9YbaMa+vt+iRXz+viYn6emYO7M+zA53N/UoXlL0mnpmMbtJO6H/Roq4hk5P9RZOr9gmOUxWHVZ7nix8MMHyfAnqgdyrv66+WU=,iv:s0j0FYRAGKaYHSahf5bmcCQ9IQsqhgmYABw6ygU2vME=,tag:C08hwzQX8X/0MIsJuQpRag==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Hcur2Mclv7SqRn3XD/DCTr23RRbWnwEpdNE/rev3Oq6YcutBhoulOcicsMKkpWYk,iv:557YxHlZUHARPlH67aOdXqm0TegZjKy1TEiZJ2QxU6A=,tag:A3UjAhAn4rxfParlemD3uQ==,type:str]
sops:
    age:
        - recipient: age17s2hrj0xgegzxsq6h3shdy94etlnec2amyz787pjj30wl72exqxq57uumr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaEl4L0lCNmlueGFBbWp0
            N1lSbkVQN0xnR2l1K1lRcUdDeDloNUpKY3dJClpCcERuVlFmZlZpSXlKQnNSMnE3
            QjZwNkUyT2psdFhrbXNlTXg4YmE2L00KLS0tIEN1aklzaGJWVDRaSzBzaXM0NzNq
            UytVdys0bElUM2JVMXoxRnZwS1Z0MlEK9X6QiJ8h8CC3xd3Xhsaks2jAmA2OwAmy
            17BWxuOJed9A80vx0GcF5ePh4l4xYZEcvQRK36IXnl+AmeJ0AwM4Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T11:49:11Z"
    mac: ENC[AES256_GCM,data:GFLRBCA+r3AHYN1trlZMw52Z1zGanh8xuy3Ogssa+ocORXeyd1XcB8CiitByPsI5U8IyYb2MvOGPyrMjVYmY6jC+HuDzxFQAMZNC4J1KqMayKpzhkhLVqDVYg7o1+TdupKUhKP0Ri1akoZ+TC9hjMfyDKDhGyHGHp+JO+a4GdYA=,iv:etEe8yRYrIzSSdkkmmVcKM+OtWEJsXWIyd8Z2kkBhi8=,tag:cI2FPvsEV0SC+AetS8YCZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
