apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:0HfFGSLGsAt4HRpPUc5hJLBuW1m/uzDhsvknmEjn7QC88QoM20yDV0xAj4O1kWZVPoogtiNQAe/KhOj8QKHBLy+BrAbPSKbqAswbDzqKc1M31fIwLhQJEg==,iv:8X1rxbM7ioxupXLhgZUXuxLbzBSJM1IF502LSCaQAik=,tag:r67rFLZ++oT6nO59VigLRQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:49qaalcia4PrX1bH0sP9iSQanjcR8HYf4FBLGWUm3vjWpvTtIbl4nqDVg5n/zwqRhj8/tY5vdJTLDa4/y/c62A==,iv:FFZOw1jqXFc95NMIXLHUsKgVbrYgQPGBuAoYrFYRQKk=,tag:uq9JPRXJcz+tPTMAv8ML8A==,type:str]
sops:
    age:
        - recipient: age17s2hrj0xgegzxsq6h3shdy94etlnec2amyz787pjj30wl72exqxq57uumr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UzkxalR6Nm5nU2Z4RkZW
            RWpJaGMwbmlEVE1WVFBKbnJpN2RnUWttbkc0CitqM1E2ejhWS0laMDRtTTVWSWl2
            cFpLQUVhdU80TjBFVE5NRmJ0VGY5bU0KLS0tIExnZjRxTjFqUGhsK2trd090Q3pj
            WTU2L0l2ZFFNd1l2L3FqbkJTekhuTDAKZDyo/RuuRnk62qh8pQEe+cpMLTaZei2B
            PiPMyTYj384hUJXZAOCtW6ufIiUpnRg0pRY5B/1JZWvlbe4nXDYKUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T11:36:31Z"
    mac: ENC[AES256_GCM,data:FvJIvf5/AgheAGDpvcYbvpPNFjBgDM7sI71keOQQWbXTzzsq5Ol6EfH56wqHQhVk4DiJzRzRasAd3bTMzSqbTPdXHWg31R51nSeI371gdvrGOiHjpb+J5hwxcflGNjPy/4PYTXlbk2Qq0NRyxtoDIzU0ZE4VTjRQNwCgsbjS3ZQ=,iv:z6450FxtYIuvZlH1lgTvKjkEmZgfaxnP8Bd/bQwbJmg=,tag:n1Na/GEOIQG03IsDZuJvcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
