replicaCount: 1

image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    enabled: true
    type: ClusterIP
    port: 7878

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 5Gi
    accessMode: ReadWriteOnce

  data:
    enabled: true
    existingClaim: nfs-pvc
    mountPath: /data


ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: radarr.homelab
        paths:
          - path: /
            pathType: Prefix