replicaCount: 1

image:
  repository: linuxserver/radarr
  tag: 5.21.1.9799-ls266
  pullPolicy: IfNotPresent

nodeSelector:
  role: arrstack

service:
  main:
    enabled: true
    type: ClusterIP
    port: 7878

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 5Gi
    accessMode: ReadWriteOnce

  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/data
    mountPath: /data

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: radarr.homelab
        paths:
          - path: /
            pathType: Prefix
