replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    enabled: true
    type: ClusterIP
    port: 8989

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 5Gi
    accessMode: ReadWriteOnce

  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/data
    mountPath: /data

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: sonarr.homelab
        paths:
          - path: /
            pathType: Prefix
