replicaCount: 1

image:
  repository: ghcr.io/linuxserver/wikijs
  tag: 2.5.307
  pullPolicy: IfNotPresent

nodeSelector:
  role: arrstack

service:
  main:
    ports:
      http:
        port: 3000

persistence:
  data:
    enabled: true
    mountPath: /data
    size: 5Gi
    accessMode: ReadWriteOnce

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: wiki.homelab
        paths:
          - path: /
            pathType: Prefix
