apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfa-go
spec:
  replicas: 0 # TODO: Find / Develop a alterative for this app
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-1
