apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:1.33.3.5008-ls114

        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: DOTNET_SYSTEM_NET_SOCKETS_IPV6SUPPORT
          value: "0"

        securityContext:
          allowPrivilegeEscalation: false

        ports:
        - containerPort: 9696
        volumeMounts:
        - name: media
          mountPath: /data
        - name: config
          mountPath: /config

      - name: flaresolverr
        image: flaresolverr/flaresolverr:v3.3.21
        env:
        - name: LOG_LEVEL
          value: info
        ports:
        - containerPort: 8191

      volumes:
      - name: media
        hostPath:
          path: /mnt/data
          type: Directory
      - name: config
        hostPath:
          path: /mnt/data/configs/prowlarr
          type: Directory

