apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: 1000           # Force the whole pod to start as user 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true         # Kubernetes will block starting if not non-root
        supplementalGroups:
          - 44                    # Video group (for GPU access)
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:10.10.7
        ports:
        - containerPort: 8096
        env:
        - name: JELLYFIN_ServerName
          value: "saharserver"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"

        securityContext:
          #privileged: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

        volumeMounts:
        - name: media
          mountPath: /data/media
        - name: config
          mountPath: /config
        - name: dri
          mountPath: /dev/dri
      volumes:
      - name: media
        hostPath:
          path: /mnt/data/media
          type: Directory
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory
      - name: config
        hostPath:
          path: /mnt/data/configs/jellyfin
          type: DirectoryOrCreate
