apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-no-backup
  resources:
    requests:
      storage: 15Gi
