apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-config
  resources:
    requests:
      storage: 10Gi
