apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threadfin-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-no-backup
  resources:
    requests:
      storage: 5Gi
