apiVersion: v1
kind: Secret
metadata:
    name: aws-eso-credentials
    namespace: flux-system
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:ijQEE0qXRDUDUQudeUpH5GXDHGE=,iv:D3MCCnTFyDNJlI4d+IpCs6E0EfRHqowlHwNv365AQCk=,tag:CTOHtfjzSCVuqMwojEnZiA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:I0oysJqidmXrEgCSKxu5Fy7sk9f8iXV4xSkJUfeRqc/q1LeldFZC7Q==,iv:/QdIgUtGNkWMspLaTkjPyJIZNqgA1ZQXy1gWEcPTFuI=,tag:QRPy8iQPJtxL5IYvEZfRuA==,type:str]
sops:
    age:
        - recipient: age17s2hrj0xgegzxsq6h3shdy94etlnec2amyz787pjj30wl72exqxq57uumr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bFNyem00cXlxNlg3cDNF
            V295ZTJ4SHZJT0tMMEkwSWl0UlZrQkl5QnpnCkpPSUxDQ1pLajJZd3JGTkgxakZO
            K01xZ2NsT3VacXQvNjBIRCtBRzRRY0EKLS0tIHp1aFg4ekk1T3FyeEs2YVB5T1Q2
            T1NMQVNoMnBTSks1a3dEdUlmejJIYUkKCSlJyPu5TcM9PCsUtnLl7gWtgiw8GnQA
            yD4l+nTYej9SycFMhNVsU/dSeaN+hoDWhwFjSsjRtg/j7i131lzv0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T13:27:47Z"
    mac: ENC[AES256_GCM,data:ZooJLFtUg4tDohIeEYR2cH2qGNh2TOFLkoq1VmAdSnkNi9NquW9m4BhUMeQbThDIgu1ntS6FhtDSXwwJkZp7DldxSI5yzmlJQ8edXFfFJzy1oB++WDZ1H+YtF+YNgR37MPpaDlq+JSBlqP1td/E3HfwZaSQ64RssHTC892zb4MU=,iv:oAd4imfHCa4Cf5zwLSo+YxdW35wAv7OhuHaxiqRNbDs=,tag:VlBZ/Wr8GW2yxsCeG4Cxcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
