apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-eso-credentials
            namespace: flux-system
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-eso-credentials
            namespace: flux-system
            key: secret-access-key
