apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: aws-secret
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /homelab/longhorn/AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /homelab/longhorn/AWS_SECRET_ACCESS_KEY
