apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: v1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn-system
  install:
    createNamespace: false
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }

  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      defaultFsType: ext4
    defaultSettings:
      defaultReplicaCount: "1"
      backupTarget: "s3://homelab-sahar-backups@us-east-1/"
      backupTargetCredentialSecret: "aws-secret"

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      host: longhorn.homelab
      path: /
      tls: false

    longhornUI:
      replicas: 1
