apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 30
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2025.7.0
        command: [ "cloudflared", "tunnel", "--no-autoupdate", "--loglevel", "debug", "--metrics", "0.0.0.0:2000", "run" ]
        ports:
        - name: metrics
          containerPort: 2000
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits: { cpu: "200m", memory: "128Mi" }

        # Let it fully establish the QUIC connections before liveness kicks in
        startupProbe:
          httpGet: { path: /ready, port: 2000 }
          periodSeconds: 5
          failureThreshold: 30 # ~150s

        readinessProbe:
          httpGet: { path: /ready, port: 2000 }
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:
          httpGet: { path: /ready, port: 2000 }
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 5 # be generous; brief disconnects are normal

        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh", "-c", "sleep 5" ]
