apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer

    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      initContainers:
        - name: fix-permissions
          image: busybox:1.37
          command: ["sh", "-c", "chown -R 1000:1000 /app/config"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /app/config

      containers:
        - name: jellyseer
          image: ghcr.io/seerr-team/seerr:v3.1.0

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          ports:
            - containerPort: 9696

          volumeMounts:
            - name: media
              mountPath: /data/media
              readOnly: true
            - name: config
              mountPath: /app/config
      volumes:
        - name: media
          hostPath:
            path: ${BASE_PATH}/data/media
            type: Directory
        - name: config
          persistentVolumeClaim:
            claimName: jellyseer-config
