apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer

    spec:
      containers:
      - name: jellyseer
        image: fallenbagel/jellyseerr:2.7.3

        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"

        securityContext:
          allowPrivilegeEscalation: false

        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        ports:
        - containerPort: 9696

        volumeMounts:
        - name: media
          mountPath: /data/media
          readOnly: true
        - name: config
          mountPath: /app/config
      volumes:
      - name: media
        hostPath:
          path: /mnt/data/media
          type: Directory
      - name: config
        persistentVolumeClaim:
          claimName: jellyseer-config
