apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseer
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: jellyseer.homelab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyseer
            port:
              number: 5055
