apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secrets
  data:
    - secretKey: admin-token
      remoteRef:
        key: /homelab/vaultwarden/admin-token
