apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: homarr-secret
  data:
    - secretKey: SECRET_ENCRYPTION_KEY
      remoteRef:
        key: /homelab/homarr/SECRET_ENCRYPTION_KEY
