---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-db-encryption
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: homarr-db-encryption
  data:
    - secretKey: db-encryption-key
      remoteRef:
        key: /homelab/homarr/db-encryption-key
