---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blackjack-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blackjack-web

  policy:
    semver:
      range: 1.0.x