---
apiVersion: v1
kind: Service
metadata:
  name: blackjack-web
  namespace: default
spec:
  selector:
    app: blackjack-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30801
  type: NodePort