apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huntarr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: huntarr.homelab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: huntarr
            port:
              number: 9705
