apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utils

# deprecated telegram bot.
# TODO: Make it better and deploy it again
#
# resources:
# - ../../../base/utils/telegram-bot/
