apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: tracearr-secret
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /homelab/tracearr/JWT_SECRET
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: /homelab/tracearr/COOKIE_SECRET
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /homelab/tracearr/DB_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: /homelab/tracearr/DATABASE_URL
