apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tracearr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - tracearr.homelab
    secretName: tracearr-homelab-tls
  rules:
    - host: tracearr.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tracearr
                port:
                  number: 3000
