apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-config
  resources:
    requests:
      storage: 5Gi
