apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - longhorn
  - media/bazarr
  - media/jellyfin
  - media/jellyseer
  - media/notifiarr
  - media/prowlarr
  - media/qbittorrent
  - media/radarr
  - media/sabnzbd
  - media/shared
  - media/sonarr
  - media/tracearr
  - monitoring/blackbox-exporter
  - monitoring/kube-prometheus-stack
  - utils/cloudflared
  - utils/immich
  - utils/moneyman
  - utils/n8n
  - utils/server-hub
  - utils/vaultwarden
