apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent-vpn
      sourceRef:
        kind: HelmRepository
        name: rtomik
        namespace: flux-system
      # version: "x.y.z"   # optional pin
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  values:
    podSecurityContext:
      runAsNonRoot: false
      runAsUser: 0
      fsGroup: 911

    service:
      type: ClusterIP
      port: 8081

    qbittorrent:
      enabled: true
      bittorrentPort: 6881
      service:
        port: 8081
      env:
      - name: PUID
        value: "0"
      - name: PGID
        value: "0"
      - name: TZ
        value: "UTC"
      - name: WEBUI_PORT
        value: "8081"
      persistence:
        config:
          enabled: true
          existingClaim: ""
          storageClass: ""
          accessMode: "ReadWriteOnce"
          size: "2Gi"
          mountPath: "/config"
        downloads:
          enabled: true
          existingClaim: ""
          storageClass: ""
          accessMode: "ReadWriteOnce"
          size: "50Gi"
          mountPath: "/data/torrents"

    probes:
      liveness:
        enabled: true
        path: /
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      readiness:
        enabled: true
        path: /
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1

    gluetun:
      enabled: true
      securityContext:
        privileged: true
        capabilities:
          add:
          - NET_ADMIN
      vpn:
        provider: "nordvpn"
        type: "openvpn"
        serverCountries: "Israel"
        randomize: "true"
        openvpn:
          OPENVPN_PROTOCOL: "udp"
      credentials:
        create: false
        existingSecret: "vpn-creds"
        usernameKey: "username"
        passwordKey: "password"
      settings:
        FIREWALL: "on"
        FIREWALL_INPUT_PORTS: "8081,6881"
        FIREWALL_VPN_INPUT_PORTS: "6881"
        FIREWALL_OUTBOUND_SUBNETS: "10.42.0.0/16,192.168.0.0/16"
        DNS_ADDRESS: "1.1.1.1"
        SERVER_ALLOWLIST: "qbittorrent:8081"
