apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent-vpn
      sourceRef:
        kind: HelmRepository
        name: rtomik
        namespace: flux-system
      # version: "x.y.z"   # optional pin
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  values:
    podSecurityContext:
      runAsNonRoot: false
      runAsUser: 0
      fsGroup: 911

    service:
      type: ClusterIP
      port: 8081

    persistence:
      enabled: true
      config:
        size: 2Gi
      downloads:
        size: 50Gi

    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3

    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    gluetun:
      enabled: true
      credsSecretName: vpn-creds
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
      env:
        VPN_SERVICE_PROVIDER: nordvpn
        VPN_TYPE: openvpn
        SERVER_COUNTRIES: Israel
        FIREWALL: "on"
        FIREWALL_INPUT_PORTS: "8081,6881"
        FIREWALL_VPN_INPUT_PORTS: "6881"
        FIREWALL_OUTBOUND_SUBNETS: "10.42.0.0/16,192.168.0.0/16"
        DNS_ADDRESS: "1.1.1.1"
        OPENVPN_USER: ${username}
        OPENVPN_PASSWORD: ${password}

    qbittorrent:
      enabled: true
