apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 10.0.0.20
      containers:
      - name: homarr
        image: ghcr.io/homarr-labs/homarr:v1.39.0

        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"

        securityContext:
          allowPrivilegeEscalation: false

        ports:
        - containerPort: 7575
        envFrom:
        - secretRef:
            name: homarr-secret
        volumeMounts:
        - name: appdata
          mountPath: /appdata
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: homarr-config
