apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-admin-lite-binding
subjects:
  - kind: ServiceAccount
    name: tf-runner
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: helm-admin-lite
  apiGroup: rbac.authorization.k8s.io

