apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "aD6ECjHXljRQKR+tRYzf9dNk7qyyxf2bycJA7S6njjZpD/7KgRDHzpdPziFLEhbTPfRhVRBQCRfkZI/kRk8yKg=="
  POSTGRES_PASSWORD: "K/VwyEyPqyi7OvGMV8BZfZigqb1YOjBabcJLCpcwgwfGJyeVuRy0XIuiL2IPpEJq"
