apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-url
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: discord-url
  data:
    - secretKey: address
      remoteRef:
        key: /homelab/discord-alerts/address
