apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  suspend: false
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kubeProxyReplacement: false
    enableIPv4Masquerade: true
    bpf:
      masquerade: true
    extraConfig:
      enable-remote-node-masquerade: "true"
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2
