apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: telegram-secret
  data:
    - secretKey: AUTHENTIK_API_TOKEN
      remoteRef:
        key: /homelab/telegram-bot/AUTHENTIK_API_TOKEN
    - secretKey: AUTHENTIK_URL
      remoteRef:
        key: /homelab/telegram-bot/AUTHENTIK_URL
    - secretKey: BOT_PASSWORD
      remoteRef:
        key: /homelab/telegram-bot/BOT_PASSWORD
    - secretKey: CF_ACCESS_POLICY_ID
      remoteRef:
        key: /homelab/telegram-bot/CF_ACCESS_POLICY_ID
    - secretKey: CF_ACCOUNT_ID
      remoteRef:
        key: /homelab/telegram-bot/CF_ACCOUNT_ID
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: /homelab/telegram-bot/CF_API_TOKEN
    - secretKey: JELLYFIN_URL
      remoteRef:
        key: /homelab/telegram-bot/JELLYFIN_URL
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: /homelab/telegram-bot/TELEGRAM_BOT_TOKEN
