apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-hub-data-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_ROOT}/server-hub
  claimRef:
    namespace: utils
    name: server-hub-data-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-hub-data-nfs
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeName: server-hub-data-nfs
  resources:
    requests:
      storage: 1Gi
