apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: moneyman-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: moneyman-secret
  data:
    - secretKey: MONEYMAN_CONFIG
      remoteRef:
        key: /homelab/moneyman/MONEYMAN_CONFIG
