apiVersion: v1
kind: Secret
metadata:
    name: moneyman-secret
type: Opaque
stringData:
    MONEYMAN_CONFIG: ENC[AES256_GCM,data:skbeZ1+83vsSClCB34q5EU2Z6/vKpSfBkIVTlNTVaXJ6LpnZBamZ1JIRyMby+0VZkHPZl3/k9U+tWnguK27xcjoO1py89cE61RloFg+jcba4X83uDLnfwbyHMg6WN/tvmAJCMZBqTZhJgsiGbl2lRJ0A9na6+RyHSzN5VI7BBsDNs3FiARJJkNDdRwEnYsTUbq4GzNTqq9R4znzWGcJNRPmL4p8spcvQx8lY6xpsMk02nBlo4KUPLn7gtXYT0EvIylopEqEFRxr1DUaYRpeve10MRWglnFkIOmtFghiDNiimAFJ4Y76OWzc5TbAky4kmOn09b3Do3Yhz8M43/ywDnTGfCd7/qz2H81p2+DwXPBERi5WESfMO5tMs/Ef7fWcoZ4mDcJUnKTbvoiwDsHZK8JYm+Ra1EmzocNhpuyC1ciIzDrxBUUoTEaYKQlHwRzIwLE9FIKsghZ0AWb4+z0nq04uJLGgyr5FPt4Ko2UN21rPV4hWyt/3FWg51rbCUeS8lPAnuoJtTmSZtdDJgpHaDZi3KhCKqiQgjiJJ6kWNxzVDmtN8Iyv6TCJEI4oVUARw35TN0qPSMNROPFJ3zWAXMpkLztJXD53+pTbLGWegYNHzqeiiCTBg4S9GEvv6zhvM2RIwNM4sWLMJPGmrfdshW+408lAberSKjK0sll6yqBp48zbP38xvjWDBo/8VA8tXs/9g68HahJp7NlyTMERdpj9dQuoLwYirKFfSE2boE+QC2RIx0JwHWn4thIt/LK+WYSVOwtLl+MOW5t2R2rPatKb0nw4XQuZ3gP76fXAUARVtekjpRpya4/DGdzI8Lrsl6+SIma59hcJxq2sfz/l1MDyASYvIcaYI7h0KUdOb2u5ouXsDRaq5kal0zSOUgDp6NawEeJpnTzWHIqs8M5GaiDI5ZSqzB5gkdVm9+NftJWkpx+2MvKmx3JfudRYcv3VL7fiLZv2UZzTa46omT65/+97jEQhgJQKJMZgRV7Hf2HSmcDILX2tFWZ7n/PW2ggRRaNZcmiFzQEbLKrZr1fyLISwXLfUHmhpd/Gy9OnJL0/Na6r5jmeP8jvZIX2FhklCyy0Cir17w0rkoIdlgIbg6EV29teWDUHudBi+m45Vohqg8uHeAvCVRjOYbrWDNmjITGJG+1iG/C2EBExA6ERipbO1aMinpspoJ40o+4BKcDYPeey1zlox2kjbvIPttHDZEmGnprUo0Qw77r+68m4CNcK+boWkNJpVCUldBllJDq7rP9qrUcZEUmqtsqavqfzsRsxDDO44xZ/hILBqV/yMqZBIW1W7mv2ogAvB2YP2QmrkpUI0q1yltEpM/kvrVXaEpWbx0tPUogROrDJTUDrw==,iv:m1UzNsSDZezY9oUUIZJzYQCsPWZcYsmHPtTiN1vlTAA=,tag:So50CEwgNXGQ42I2YHok4w==,type:str]
sops:
    age:
        - recipient: age17s2hrj0xgegzxsq6h3shdy94etlnec2amyz787pjj30wl72exqxq57uumr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcDcxeFcxNUFYYnFaVVdT
            ZEV6N0dEMzhON0NCVHZDS2ZMdURGY1ZTWUIwCklsQ3ZzNUwwWHZEQ3FoN1ZZUGdp
            NEVaR1dQTHJBS3BQaEdsa1hXMVR4Q1EKLS0tIHU5ZDNqRlNaVFpxc1lEdzBMU1pP
            WHF5M0NoQkdRdnJoZ0Z1V0F4UUlaSG8KDZkK0eb6bfjemMzp8psjGcFgoJp901Mn
            ykbo1gp6hIMy4agS4ohUsl6g7LQkPLQ/dv8rKKn+w1qNOAziGmmP4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T10:28:08Z"
    mac: ENC[AES256_GCM,data:ei467glrfZ7UeFwFGAJVg+ulCEdD2vhLTt5hB2rldC7ReUn5A7traWZZfnxvgxyHq1Zx3s8gEJYOCBqEuTRq+TH2zpAmTsbvNzKMWB/8Or9ACygKMtjtgQANblBkA7kRLTKj6w0eSZ6JgtflrO0go8c0lTAhHlIT7O2HKZqcC0c=,iv:dje04HzteAJL5wOjzhxO/5QXPkUHojzHUXKEIVjwJwc=,tag:F39BkWxR0DoliVy/RPs9xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
