apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: moneyman-config
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "/homelab/moneyman/MONEYMAN_CONFIG"
        objectType: "ssmparameter"
        objectAlias: "config.json"
        filePermission: "0400"
