apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: splitwise-ynab-sync-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: splitwise-ynab-sync-secret
  data:
    - secretKey: SPLITWISE_API_KEY
      remoteRef:
        key: /homelab/splitwise-ynab-sync/SPLITWISE_API_KEY
    - secretKey: YNAB_ACCESS_TOKEN
      remoteRef:
        key: /homelab/splitwise-ynab-sync/YNAB_ACCESS_TOKEN
    - secretKey: SPLITWISE_GROUP_ID
      remoteRef:
        key: /homelab/splitwise-ynab-sync/SPLITWISE_GROUP_ID
    - secretKey: YNAB_BUDGET_ID
      remoteRef:
        key: /homelab/splitwise-ynab-sync/YNAB_BUDGET_ID
    - secretKey: YNAB_ACCOUNT_ID
      remoteRef:
        key: /homelab/splitwise-ynab-sync/YNAB_ACCOUNT_ID
