apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
type: Opaque
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:SIRR1tE=,iv:TzScNe1RfArcPGVh+fF5cUDPgB1IYvKD++HgzivsGy0=,tag:DFK44KrXAp8LU3JGguT0RA==,type:str]
sops:
    age:
        - recipient: age17s2hrj0xgegzxsq6h3shdy94etlnec2amyz787pjj30wl72exqxq57uumr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTjVwRHcramZVM3J2bG1m
            SXFpdXhjaTdNZVI1UmEzK2IwQldWK2xWdkNnClc1bWh4SlQ3ZVJtQzhzVmd5Vi85
            cmtyRWExeW9PR0RIY2VjVnJTWGkzQmMKLS0tIEdCcVVKOVljbVlkMFRETmloQlk4
            K3I5WXI4QU14TEhRT1N4aVdmY0dKeUEKmSULwlE6B+BjtwibvUdIPJaqLrnOk8Y5
            IXk+rE/a1tEiNLoS/GeRNfZZiHYgJ2rn2SUuVNXt9DloHj+hY9Z/oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T14:26:17Z"
    mac: ENC[AES256_GCM,data:WIRL6pQGVX/wX/D1LJGusX9PPibVGV/lnmmW/jYweC1IRjNcA2Ku2igZe0f+t8ZTUHfgGnBa5voeLZbadCsy8Id5q5dYHLJonTOSfFLZMP61poradEjlOrJid05SwGJ8/F27BFVTYg3S//C2AwZcqVmffmHXWByPOh6YBiLOyjs=,iv:HYFo4F0ElO9JNSyDEGK7DHSoohphmqvSE/jK/8/oFDo=,tag:6hXPzKB9r+SEflrNWYYYHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
