apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: external-dns
type: Opaque
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:xSz3v7c=,iv:fh1OBMMEZOngQR4FUdYL5wcx5ICdNVK0ENnw+mgHxMY=,tag:tHl/8TBXNk47PVuvLyueYQ==,type:str]
sops:
    age:
        - recipient: age17s2hrj0xgegzxsq6h3shdy94etlnec2amyz787pjj30wl72exqxq57uumr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYXJrS3l3T2NYVmVwNFhE
            dE1rL2taR3pSNC9YVkllMjViYUV3bHRSbUhVCjZMWnZIRVU2VVZmdGZIVVY1Q0Z3
            UmlNalUyT2VQY1pqaEhuWGdyWTdqWEUKLS0tICt3Yy9aekluK3JSejJHWGlvNXk0
            VDRSSUdJbkptTFUzMkN4QzM0S3doMmcK6s37t3EJw4JTAQmURrTPnZ1cfgsbbAMl
            a1uqZavjZFqzJN1A+OHMSHuVUNpDCoikHhDe8O86iwtu8iaOX08dKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T15:06:06Z"
    mac: ENC[AES256_GCM,data:SNssXMsTPO1YlEhkl2J3LyiCwilZMjefskTV4d1n8xuZWLbZWBBG2uZL+gKIaUVD7u9BAxWkkqDs91diRl12ztUiZoxK/rypCDyz3THaeHVKkkHynP/JjU9PoI5kGs2njNWGYOKrJG21NvPCr8ANp6BgwWMSv4hhEkCzuIM7A0Y=,iv:VOAbX7hex5fhPWfpPkTyFaLLv+MAH6YqrnivMfAz82A=,tag:ERKhAJklw2SVqGezcgZ0Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
