apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-nfs
spec:
  capacity:
    storage: 10Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: ${NFS_SERVER}
    path: ${BASE_PATH}/data
  claimRef:
    namespace: media
    name: media-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ""
  volumeName: media-data-nfs
  resources:
    requests:
      storage: 10Ti
