apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        tty: true
        stdin: true
        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "1.20.1"
        - name: TYPE
          value: "AUTO_CURSEFORGE"
        - name: CF_SLUG
          value: "better-mc-forge-bmc4"
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: curseforge-secret
              key: CF_API_KEY
        - name: MEMORY
          value: "6G"
        - name: USE_MODPACK_START_SCRIPT
          value: "false"
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "8Gi"
          limits:
            memory: "12Gi"
      volumes:
      - name: data
        hostPath:
          path: /mnt/data/minecraft
          type: Directory
