apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft-server
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    nodePort: 30565 # Pick any free port in range 30000-32767
