apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-data-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_ROOT}/n8n
  claimRef:
    namespace: utils
    name: n8n-data-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-nfs
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ""
  volumeName: n8n-data-nfs
  resources:
    requests:
      storage: 1Gi
