apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:4.5.3

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"

          ports:
            - containerPort: 8080
          volumeMounts:
            - name: downloads
              mountPath: /data/usenet
            - name: config
              mountPath: /config
      volumes:
        - name: downloads
          hostPath:
            path: /mnt/data/usenet
            type: Directory
        - name: config
          hostPath:
            path: /mnt/data/configs/sabnzbd
            type: Directory
