apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_ROOT}/sabnzbd
  claimRef:
    namespace: media
    name: sabnzbd-config-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-nfs
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ""
  volumeName: sabnzbd-config-nfs
  resources:
    requests:
      storage: 5Gi
