apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackjack-web
  template:
    metadata:
      labels:
        app: blackjack-web
    spec:
      containers:
      - name: blackjack-web
        image: ghcr.io/saharariel/blackjack-web:1.0.3
        ports:
        - containerPort: 8080
