apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-web
  labels:
    app: blackjack-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackjack-web
  template:
    metadata:
      labels:
        app: blackjack-web
    spec:
      containers:
        - name: blackjack-web
          image: ghcr.io/saharariel/blackjack-web:1.0.4 # {"$imagepolicy": "flux-system:blackjack-web-image-policy"}

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          ports:
            - containerPort: 80
