name: ci
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  homelab-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Block plaintext Kubernetes Secrets
      run: |
        if grep -RIl --include \*.ya\?ml -e '^kind:\s*Secret\s*$' . | xargs -r awk 'BEGIN{p=0} /^sops:/{p=1} END{if (NR>0 && p==0) exit 1}'; then
          echo "No plaintext Secrets found"
        else
          echo "::error::Found plaintext Secret(s). Use SOPS."
          exit 1
        fi
